DEPOSIT = 1
WITHDRAWAL = 2
INTEREST = 3

TRANSACTION_TYPE_CHOICES = (
    (DEPOSIT, 'شارژ'),
    (WITHDRAWAL, 'برداشت'),
    (INTEREST, 'Interest'),
)

MINIMUM_DEPOSIT_AMOUNT = 10
MAX_DEPOSIT_AMOUNT=10000000
MINIMUM_WITHDRAWAL_AMOUNT = 10
MAX_WITHDRAWAL_AMOUNT=3000000