# Generated by Django 3.1.5 on 2022-07-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0002_auto_20210902_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersignup',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
