# Generated by Django 4.0.2 on 2022-07-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0003_auto_20220713_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersignup',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
